language: node_js

node_js:
  - "8.9.4"

before_deploy:
  - echo "Installing cf cli"
  - test x$TRAVIS_OS_NAME = "xlinux" && rel="linux64-binary" || rel="macosx64"; wget "https://cli.run.pivotal.io/stable?release=${rel}&source=github" -qO cf.tgz && tar -zxvf cf.tgz && rm cf.tgz
  - export PATH="$PATH:."
  - cf --version
 
  - echo "Installing cf blue-green deploy plugin"
  - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
  - cf install-plugin blue-green-deploy -r CF-Community -f
  - export DEPLOY_TIMESTAMP=`date +'%Y%m%d-%H%M%S'`

deploy:
  # on update to master branch we deploy to Cloud Foundry
  - provider: script
    skip_cleanup: true
    script:  ./scripts/cf-blue-green-deploy.sh blue-green-cf-travis manifest.yml prod
    on:
      branch: master

after_script:
  - echo "Run your full suite of automated regression tests here"
env:
  global:
  - secure: pOnIR1sC5JkQPMJSCzoSpvLdhD8109cKCfAiR2zHeLBGnXJnJ3P1X4MZlDxMERJ2K8j+4foqtbp4euUX9u+mUf8TTt90i/vVC3Ggmun5mR6zKlMq2qDaIGLdmI7ETPlEj+Qeoh9ZuMyNX6ivOk02iHRodEqMMp9Pj/qii9IWbw223/AZtNDun7DTrjH2bMLhsdticdxxKz7aFe8FE5WUX2Iti2MnNl04/FN/hqczqUfnH4QoemU4iqp5Fpz9x+K+9wEPLKirFbgMyMR6eTIl3Nocjv3DxTBUxREBCGdVCZWH4CqV1vWKvou9h7AMyIF6w5vt0LDO9zu77Hl69oVmcG8bF0qI3TM2e2Ecg5TqSdNhN4G3/fWCnUFysQEZxU20WzmaGCIFyewAl6D3Fg5SCtL+1vDFt+VJyGldVsoBYnx1E7Vpx8VnsS9W+xBvRZDCs+T+uR51QVATLoaVSPjRJIe8gd+645MpG/2J2HnidNJoEXhYePuNr7qCG2ztssITPlzaucsE2Po8uO6+74npUNF3XZUPMOlFWJ0iCL6bp1mmpvNvZMLnXLcJ2V4i6iself7TNnFRQ46Hrcm38ivRwbSYHuu+6jnPdaSE3oLRrHkV9y32jevztkGhVjcKLs9Cg1fsZakvSOAjWhJN2AnlT5GU2SME6Whj75klRuPHIy0=
  - secure: dq6PE3Iixntb2oxWpOsWw8hDJOOSu2jQaeUAMH+bEILAyj1DWXSd/431Svuw3GX6Ts2486yu1mjpduVDkp7ZkydH1/xwSygfMqCv6McVNNMt5yhQy6Z7W3MAmct/hIfZnMOJsJpiunsny7YHcgWY2w4EhO+IceoKlD1zl7Oydh2f5FF9LW5Kcu2sXotUvrrzBPuaSbg45WQZkJ4ZN+VOh+Myoy7juddB4LF/0wWQracXbFzvPKf3FfKf9PE5qTXB7UENymYnlhn44CNjC+YCZkI3j8kNjw4SBT8qizTAg9VPSqRbTOGqH4XSrqlVIs7KfWK3rBnArMMZfw7fEevJ0yBvsNl5yT/6xA3VZZxxCzpMu2LsddBIh668g1M7rI2hpiqk/Yh14q80QZCzK9yoJqMMO4mKUPwJPTDH9C6bJ+VFBTnSxSCFpsE+njpjmhJuUN1+wLXXUt/BUn+eSPm8sVD/y/mZm+Vaa3RHkywwCnscsmRAaoF0/1LEn608S8ywdKuZtcyxxBgmmClHiVDmjRE0lEXpvGGwpKw5YlKQUIQJdQQwZAvDcaww4sy3ykFvblVtBIV4oSpfsVRncUxKhFN73yZBm0jEudukCpV2SJwN8L8krr9LLhsJ5DtuPPfr+pvPpzhd74CDOFegrrW4ERnYQSVGB9OlQvXkTvsF8b8=
  - secure: NzDO5H3yh9jSNdfq7cQcI6k18e/v8a0XRctUTm0wYYI2hrBAtUt0Xatis5yt4mfimkWY7aF4rkwzGRp7QudCFdqZzA7wLnJf7ctXjEUuHdUo4I//TFqZoVsgKbabbcf0nM0fUofCXn0rBtty+jLsJEIo5xCQWRMSSPQVbsVK8vhybvYtv9YKMpZDxOtiGchNQc/c5lkmx6gr9HHPj64kszM2Frr5prs59wO3bdCYw0vIMuih5QRj7/aE7ePptHbLciqgoPO4eFgUyz+oDnawky8C1wEMrftqfle60N5H8cisYuCa5M4o7NaltrXQKOojAeiw3nj/tu8eNYmRAM3CZvyDx8ELKzxTQoBmMAxRL+ZAj0xEesp1uAr1m8JpY39XDgK1UTfh6MmqmEap+ANigiz2FVrXBaTC08frQ2qnAuc26KToQf8ncbff/pDLkbX69LJGYvNCNEmTkxm8xBFVmQs6S13gj8Ln1eehkD/v8pS1Uodny+DpRH+wgG0I7Bh2/g6lAqyOvsoy/UJRRsk9CLScQ55LKmkX6Izh0uN+gf/PsFU5kJ7GlQsAt4owFMhNafNTLT449+FY7Sq+NBq0QTTbxb0L1ppljOiE+I9wZ+nQPLfY+SjsgOaFIPCzmrfIL/cDBNNcwWbEIJfJG9420pfW/GUkwj4PU9JN987LAx0=
  - secure: xWbxWTfTPReg8x+cui1QIgkAL61+50DY0Yun1TcqdLt2+OxExmTOWo8cr9/bBemueOfIqAvgv5bsM1+dwCJFRi95wcZjswocLnu+9bj8+vGJcnacxlnRfj32kE3JLLK7WeVQoeZF+8HPnC16Uyu0MauMyyhlj3Py9rLephz70c9U/d5Jp27zlgiaoWuNcg8OIzmpLaDcnltlKAK40FJFdLZegrTDAC6xOFQaa73ELexZBI/FSBxNeYk5WcSUPh5u7cqKTmui+jb3tC7ze6awXQsZzecE8BffLs2ur3qW2HtfEI/7MYpJhSa7XMnERj6hzzCFgwugEac/YEtXUQai/c+7FO2DQyNgOTzApIbLBrRlGp7U34GshQIjgM7bolKzqTEYXTL7KPq86I1cJUihqSNgREpnJpw2uqulPF5M9weSuo2UprHVDtNPkiThmoW43WSFz8JFHiXwUISOUzKGKZEmtBVKglxpgnpV5fG7EyN6DGRjB4uj3xxm0/qwamZvwSfn/lZgbyFAepG3x7jFwjZ6/Qx0UGEmq0gntDuD69Ocu9OvQYuqpTWoXJUv0Lu5JfGbZOsKlJKv4YyB5dzK2LNlNy3FcpIZI2wlysceYzC9KN8mCEH88rCTtVKQfwQYFxH8auWrb8ZgoGblZ3IlQuNWF4QFpD3taVhmYiaUNT0=
