language: node_js

node_js:
  - "8.9.4"

before_deploy:
  - echo "Installing cf cli"
  - test x$TRAVIS_OS_NAME = "xlinux" && rel="linux64-binary" || rel="macosx64"; wget "https://cli.run.pivotal.io/stable?release=${rel}&source=github" -qO cf.tgz && tar -zxvf cf.tgz && rm cf.tgz
  - export PATH="$PATH:."
  - cf --version
 
  - echo "Installing cf blue-green deploy plugin"
  - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
  - cf install-plugin blue-green-deploy -r CF-Community -f
  - export DEPLOY_TIMESTAMP=`date +'%Y%m%d-%H%M%S'`

deploy:
  # on update to master branch we deploy to Cloud Foundry
  - provider: script
    skip_cleanup: true
    script:  ./scripts/cf-blue-green-deploy.sh blue-green-cf-travis manifest.yml prod
    on:
      branch: master

after_script:
  - echo "Run your full suite of automated regression tests here"
env:
  global:
  - secure: "R7qvgHeuTZ/C9xP2SnE37ElRTvcDnkM+pdGCxdufOcupOgMZlVVu6wZ2RojUTWsBGE87IbRWINzi4zawyM8w5l9FBnmLOAavo4igvnadUwIofsZy+5tvAVSZA3ll2xsh9h9Ag6bzMJOMo20O3hFnol8QmKesW/V/barA3pxbSue0TLXW9HHCb4rbhw+YaQuL9vpBR5WcVQ2vbMT8y3VvuRmY3PIdAC/STGX/c0OaaXkIaEh0qq1sXefFawAItxu/luT2myvjNIHPTl5cYKeAtnyJ2b4uzCFI7SgLwiEhZi1yR9lYeCUTQ3JFoVqGqoT+9lipZ8VYIvym3/Qf6MMMnWeMfWTxfZJnf+2krJTSNgCZxRLZz47aJdPR4z/12muiHD/spV/6O/kc4V/OJt5ZeEweTGPOtpFd4WOXB1W3xCCURkhNSyYvr8g/Kl5xbsHW1ARLnISA9+jcUy3xqt2JKCNsM5RTajFKq6BN5zQA67KN89ew1wDLgx8CqZObEd11k924o+3cxcDHOqDg3I1jpo7ww2V9CHnvnSPAK9n8/OFvWbj6thiBdplHvdaBHaheKC2KGF/ckiQKS5xoc64p+yozHZpoSjz7/gpCLBVrlEiyAS8fUJvXEsoc9yD6hUr+AgNQx0Eao7hDXVU3f+Orv8uvQI6KGXkXEevcBcMAXE8="
  - secure: "ze+HNxreyxAUFK7TF2r2DZCo8le6iqdO5CWYEXc2wR6hZ5nq44Iqpp6s1UjlcBcTCExQVYrfEhVsDTVco1eUDhI0mnCn0E1ErF/52xgMuii5/VHRwHgT4oOmH0p5bc/YOFA1woEY7cZ7Kb4alCUkv/aguJfKY9Z+TdS4HR3c6KwMvLtwG+qL4TAZHxEMCnz8JIQBnHCMW/9Do+3IB57eFrTesm/0IILTv5roHbF/fWs5IcrAFoePOw9ulEjS2RvEs1zxBApGhLheXb/I5aR9t5gKjoVBlFeg2rc0MGGDY39dIdOz6xlpyboaJANXJl0EML7h0NT8EhKywlMh4nDPWjQoWpSbB0UfEGKhXPcXt5Est6/AaXjtoWPJuUxUG2dNemRCcZauDk0bCH+l+qeBBKKK2btSrn/BVO981iopeXrKTO4Z2p612yQ12IIU1jTOITfa7Jku4SbMDYfG+uyLa08OlEHXn6kDWZaoAUiOfHZnAdClTh097vxUeOaQJSRbzkXTy6yRLZPN/vQerd3gFfgdLwVX08Sf1cIyNSLPKm8hWOB0jiJdURzvpOkXzIBKxmmBSKRDQxYZbqOSn/kidRXIUWF+cSMwGxA7c5pWAPTOHdtxFaOaf/mjHxfzhoaEGjaHbhgPA2ORJn62bPGBF7yrawky9tJ/AZXsGh2afcI="
  - secure: "ekuS+h2ic4Rvka0Uqq91EnQP+Zu11q6z8qO1vYBmhH06EQBPW491S5YrGAGpqq1ihYhUJWLHQVSr/G/C7LOnAgaUK2HNX5OAuVPYAAlSAXWGAlR6Sfx7KNGLhob6CNeEsD+FAbj75sfmz/GatrrxRXGLL2zp4RWhKJwMUM7IBqj7YUhziQDyd3g6anTABiLaYTbOidiRzENalrZoWinnUqECi4KHvUQMOVej3lIJ5usHSlr39rndohI+tX8Wy+JHQPI6x8PkAUW/BYkOQ2yELp1tllEXk/BTwqNPjoB+5zOmvzPcXH1Mek7OsKS9kWTaE4izkn2kq5T6RXFKeqiIkotu+4dK3bA40hP1hQF9QzwV40ULm0crNfpfll1grn3CslknZZAkJRQdF4+YGrXWiosTHaC3rd1HX0NkXdf5oZtQE8hy5U1UT3Df42RrR2q1Epqtb7Y3QVSdFym+YzZ7lXhwUP0/1vE/hQ4SDR+JphB1TUUkBpXeBCfBedt5lRDV0CIWG9fMBx4mCuTcPhG3n23+IjHWOGxLrUhFze+8aiKOC9hwjktwoKqlhctbFKMHdO/wRxlo5OmP0S2WbYfVRTrO6rbRg+fPn1XwMtvHI0zdJjfqymQQjjiz5K/EA9+rth4ueFNlCYGs84nxUZ6Ow9XcB+f+9L8mSoF72QdLzSE="
  - secure: "iuGw8cLL8ThfaU716FJQtkjfseoTX5DDuQXuKRH8esvo3BCp7zBImcwGsEnmgEnqsBTq/5oZ+6tgSPq6nJJCjFTqK0Lqb2+Vyb/YNl2luMYSdw6nDs8znHHBaSiwLSKtYE5hfMQBRRo3LsAcy92wzl+igUgenOGpSJtUW91ffZR5VSSIOtWo8Kzs8YZW2oUIP9+1+QLiydqBPuWRmCB+IuQYY5EnK4EiwSKKkka8JugEzOM5QuOXnVwFE6OIdEiUjlHrjc+PM3D4m05t+JUcSq4SEx6yuOtWIiHr7QNIb/JDz75F/FHpiFnwRF8oc5xIZAyCL5ni+ntZjMxVZHWlYUntb+3TCcrPBsTphof/trOz2KqbEeDfWRjh5axN+nH7sSoMQKfa9R4gsB5uMd9oL4MOGXiMN897gg56PL7TwkYkYtMCpd8HWlMPJROlpbTj9fz0jVtXsqKY9m71dwSiLFmGo0acOSkjT4CN3/w3aoU8hkp19jlEzYJ0/ANrgHRHR7xbLAG8CgGIGBj2Kw5fgw/+tdKpZW1mE+FeyIxdR5K/3hQ+ERTr64xJcpOEGSMGE/2CvD/raTz46vUxHYXHk/9DCJqbWCEmz7nkgine7XVzJyhBGhQTXbabD4Kw+V0DFpZrr2k2XA8bWf8T7xbad1bfGcVRrhC8mkY0aXRdHWs="
